FROM java:8-jre
MAINTAINER judo xiangjunzhong <xiangjunzhong@qq.com>

ADD ./jar/judo-auth.jar /app/
ADD ./jar/pinpoint-agent /app/pinpoint-agent

CMD ["java", "-Xmx500m", "-javaagent:/app/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar", "-Dpinpoint.agentId=judo-auth", "-Dpinpoint.applicationName=AUTH", "-jar", "/app/judo-auth.jar"]
