version: '2'
services:
  judo-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
      - 1025:1025

  judo-config:
    links:
      - judo-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always

  judo-gateway:
    links:
      - judo-eureka:eureka
      - judo-auth:auth
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 9999:9999

  judo-auth:
    links:
      - judo-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    ports:
      - 3000:3000

  judo-admin-service:
    links:
      - judo-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-admin
    restart: always